name: Sage PoCs
trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'
  node_version: '10'
  dockerId: sagepocs 
  tagName: latest

steps:
- script: |
    docker-compose build

- task: CopyFiles@2
  displayName: 'Copy ARM templates'
  inputs:
    SourceFolder: deploy
    Contents: '*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
    docker-compose push
  displayName: 'Pushing Docker images'

